use constant S_LANG => 'is';
use constant S_ADMIN => 'Stjórnunarlegt tenging fyrir %s';
use constant S_ALLTHR => 'Alla þráðinn';
use constant S_BANLABEL => 'Banna:';
use constant S_BAN => 'Banna';
use constant S_CLOSED => 'Þessi þraður er lokaður. Þú getur ekki setja í það nú.';
use constant S_COMMENT => 'Athugasemd:';
use constant S_CREATETHR => 'Skapa þráð';
use constant S_DBERR => 'database villa';
use constant S_DELBYIP => 'Eyða skeyti af IP:';
use constant S_DELETE => 'Eyða';
use constant S_DELETED => 'Eytt';
use constant S_DELETEFILE => 'Eyða skrá';
use constant S_DELETEDPOST => 'Skeyti eytt.';
use constant S_DLIMAGE => 'Hlaða niður mynd';
use constant S_ENTIRE => 'Heil þráð';
use constant S_FIRST100 => 'Fyrstur 100 skeyti';
use constant S_HAX => 'hvað í fjandanum?';
use constant S_ID => 'ID:';
use constant S_IMAGE => 'Mynd:';
use constant S_LAST50 => 'Síðastur 50 skeyti';
use constant S_LINK => 'Vefslóð:';
use constant S_LOGIN => 'Innskrá';
use constant S_MOBILE => 'Farsími útgáfa';
use constant S_NAME => 'Nafn:';
use constant S_NOTEXT => 'ekki skeyti setja inn';
use constant S_NOTHR => 'þraðurinn ekki vera til';
use constant S_NOTHUMB => 'Ekki smámynd';
use constant S_NOTITLE => 'ekki titill setja inn';
use constant S_NOWRITE => 'getur ekki skrifa til skráarinnar';
use constant S_NEWTHR => 'Nýr þráð';
use constant S_PASSWORD => 'Lykilorð:';
use constant S_PERMASAGE => 'Permasage'; # TODO
use constant S_PERMASAGED => 'permasaged'; # TODO
use constant S_POWERED => 'Knúinn af %s og %s';
use constant S_REPLY => 'Svara';
use constant S_RESET => 'Eyða alla þráðinn';
use constant S_RETURN => 'Aftur';
use constant S_SPAM => 'spam';
use constant S_SQLCONF => 'could not connect to database';
use constant S_TITLE => 'Titill:';
use constant S_TOOBIG => 'file is too big';
use constant S_UNDELETE => 'Endurheimta';
use constant S_UNPERMASAGE => 'Unpermasage'; # TODO

1;
